In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

fn = []

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        fn.append(os.path.join(dirname, filename))
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/paris-housing-classification/ParisHousingClass99.88.csv
/kaggle/input/paris-housing-classification/ParisHousingClass.csv

In [2]:
df = pd.read_csv(fn[1])
df

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price,category
0,75523,3,0,1,63,9373,3,8,2005,0,1,4313,9005,956,0,7,7559081.5,Basic
1,80771,39,1,1,98,39381,8,6,2015,1,0,3653,2436,128,1,2,8085989.5,Luxury
2,55712,58,0,1,19,34457,6,8,2021,0,0,2937,8852,135,1,9,5574642.1,Basic
3,32316,47,0,0,6,27939,10,4,2012,0,1,659,7141,359,0,3,3232561.2,Basic
4,70429,19,1,1,90,38045,3,7,1990,1,0,8435,2429,292,1,4,7055052.0,Luxury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1726,89,0,1,5,73133,7,6,2009,0,1,9311,1698,218,0,4,176425.9,Basic
9996,44403,29,1,1,12,34606,9,4,1990,0,1,9061,1742,230,0,0,4448474.0,Basic
9997,83841,3,0,0,69,80933,10,10,2005,1,1,8304,7730,345,1,9,8390030.5,Basic
9998,59036,70,0,0,96,55856,1,3,2010,0,1,2590,6174,339,1,4,5905107.0,Basic
9999,1440,84,0,0,49,18412,6,10,1994,1,0,8485,2024,278,1,6,146708.4,Basic

In [3]:
pd.read_csv(fn[0])

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price,category
0,75523,3,0,1,63,9373,3,8,2005,0,1,4313,9005,956,0,7,7559081.5,Basic
1,80771,39,1,1,98,39381,8,6,2015,1,0,3653,2436,128,1,2,8085989.5,Luxury
2,55712,58,0,1,19,34457,6,8,2021,0,0,2937,8852,135,1,9,5574642.1,Basic
3,32316,47,0,0,6,27939,10,4,2012,0,1,659,7141,359,0,3,3232561.2,Luxury
4,70429,19,1,1,90,38045,3,7,1990,1,0,8435,2429,292,1,4,7055052.0,Luxury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1726,89,0,1,5,73133,7,6,2009,0,1,9311,1698,218,0,4,176425.9,Basic
9996,44403,29,1,1,12,34606,9,4,1990,0,1,9061,1742,230,0,0,4448474.0,Basic
9997,83841,3,0,0,69,80933,10,10,2005,1,1,8304,7730,345,1,9,8390030.5,Basic
9998,59036,70,0,0,96,55856,1,3,2010,0,1,2590,6174,339,1,4,5905107.0,Basic
9999,1440,84,0,0,49,18412,6,10,1994,1,0,8485,2024,278,1,6,146708.4,Basic

In [4]:
df['category'] = df['category'].replace({'Luxury': 1, 'Basic': 0})
df

/tmp/ipykernel_17/1416196371.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['category'] = df['category'].replace({'Luxury': 1, 'Basic': 0})

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price,category
0,75523,3,0,1,63,9373,3,8,2005,0,1,4313,9005,956,0,7,7559081.5,0
1,80771,39,1,1,98,39381,8,6,2015,1,0,3653,2436,128,1,2,8085989.5,1
2,55712,58,0,1,19,34457,6,8,2021,0,0,2937,8852,135,1,9,5574642.1,0
3,32316,47,0,0,6,27939,10,4,2012,0,1,659,7141,359,0,3,3232561.2,0
4,70429,19,1,1,90,38045,3,7,1990,1,0,8435,2429,292,1,4,7055052.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1726,89,0,1,5,73133,7,6,2009,0,1,9311,1698,218,0,4,176425.9,0
9996,44403,29,1,1,12,34606,9,4,1990,0,1,9061,1742,230,0,0,4448474.0,0
9997,83841,3,0,0,69,80933,10,10,2005,1,1,8304,7730,345,1,9,8390030.5,0
9998,59036,70,0,0,96,55856,1,3,2010,0,1,2590,6174,339,1,4,5905107.0,0
9999,1440,84,0,0,49,18412,6,10,1994,1,0,8485,2024,278,1,6,146708.4,0

In [5]:
df = df.drop(columns=['cityCode', 'made'])
df

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityPartRange,numPrevOwners,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price,category
0,75523,3,0,1,63,3,8,0,1,4313,9005,956,0,7,7559081.5,0
1,80771,39,1,1,98,8,6,1,0,3653,2436,128,1,2,8085989.5,1
2,55712,58,0,1,19,6,8,0,0,2937,8852,135,1,9,5574642.1,0
3,32316,47,0,0,6,10,4,0,1,659,7141,359,0,3,3232561.2,0
4,70429,19,1,1,90,3,7,1,0,8435,2429,292,1,4,7055052.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1726,89,0,1,5,7,6,0,1,9311,1698,218,0,4,176425.9,0
9996,44403,29,1,1,12,9,4,0,1,9061,1742,230,0,0,4448474.0,0
9997,83841,3,0,0,69,10,10,1,1,8304,7730,345,1,9,8390030.5,0
9998,59036,70,0,0,96,1,3,0,1,2590,6174,339,1,4,5905107.0,0
9999,1440,84,0,0,49,6,10,1,0,8485,2024,278,1,6,146708.4,0

In [6]:
df.columns

Index(['squareMeters', 'numberOfRooms', 'hasYard', 'hasPool', 'floors',
       'cityPartRange', 'numPrevOwners', 'isNewBuilt', 'hasStormProtector',
       'basement', 'attic', 'garage', 'hasStorageRoom', 'hasGuestRoom',
       'price', 'category'],
      dtype='object')

In [7]:
col = ['squareMeters', 'numberOfRooms', 'hasYard', 'hasPool', 'floors',
       'cityPartRange', 'numPrevOwners', 'isNewBuilt', 'hasStormProtector',
       'basement', 'attic', 'garage', 'hasStorageRoom', 'hasGuestRoom',
       'price',]

In [8]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Normalize the DataFrame (excluding the 'category' column if it's your target)
df[col] = scaler.fit_transform(df[col])

df

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityPartRange,numPrevOwners,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price,category
0,0.755020,0.020202,0.0,1.0,0.626263,0.222222,0.777778,0.0,1.0,0.4313,0.900490,0.951111,0.0,0.7,0.755144,0
1,0.807547,0.383838,1.0,1.0,0.979798,0.777778,0.555556,1.0,0.0,0.3653,0.243524,0.031111,1.0,0.2,0.807854,1
2,0.556731,0.575758,0.0,1.0,0.181818,0.555556,0.777778,0.0,0.0,0.2937,0.885189,0.038889,1.0,0.9,0.556630,0
3,0.322560,0.464646,0.0,0.0,0.050505,1.000000,0.333333,0.0,1.0,0.0659,0.714071,0.287778,0.0,0.3,0.322339,0
4,0.704034,0.181818,1.0,1.0,0.898990,0.222222,0.666667,1.0,0.0,0.8435,0.242824,0.213333,1.0,0.4,0.704723,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.016385,0.888889,0.0,1.0,0.040404,0.666667,0.555556,0.0,1.0,0.9311,0.169717,0.131111,0.0,0.4,0.016617,0
9996,0.443539,0.282828,1.0,1.0,0.111111,0.888889,0.333333,0.0,1.0,0.9061,0.174117,0.144444,0.0,0.0,0.443973,0
9997,0.838274,0.020202,0.0,0.0,0.686869,1.000000,1.000000,1.0,1.0,0.8304,0.772977,0.272222,1.0,0.9,0.838269,0
9998,0.590001,0.696970,0.0,0.0,0.959596,0.000000,0.222222,0.0,1.0,0.2590,0.617362,0.265556,1.0,0.4,0.589688,0
9999,0.013522,0.838384,0.0,0.0,0.484848,0.555556,1.000000,1.0,0.0,0.8485,0.202320,0.197778,1.0,0.6,0.013644,0

In [9]:
# Assuming your dataframe is named df and the target column is 'category'
X = df.drop('category', axis=1)
y = df['category']

In [10]:
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

In [11]:
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)

In [13]:
import pandas as pd
from sklearn.utils import all_estimators
from sklearn.metrics import accuracy_score
from sklearn.exceptions import NotFittedError

# Initialize lists to store results
results = []

# Get all classifiers
estimators = all_estimators(type_filter='classifier')

# Iterate over all classifiers
for name, Classifier in estimators:
    try:
        # Initialize the classifier
        clf = Classifier()
        
        # Fit the classifier on the training data
        clf.fit(X_train, y_train)
        
        # Predict on the training data
        y_train_pred = clf.predict(X_train)
        
        # Predict on the test data
        y_test_pred = clf.predict(X_test)
        
        # Calculate accuracy
        train_accuracy = accuracy_score(y_train, y_train_pred)
        test_accuracy = accuracy_score(y_test, y_test_pred)
        
        # Append results
        results.append({
            'Model': name,
            'Train Accuracy': train_accuracy,
            'Test Accuracy': test_accuracy
        })
    except (TypeError, ValueError, NotFittedError, IndexError):
        # Skip estimators that fail to fit or predict
        continue

# Create a DataFrame from the results
results_df = pd.DataFrame(results)

# Sort the DataFrame by test accuracy
results_df = results_df.sort_values(by='Test Accuracy', ascending=False)


# Display the results
results_df

/opt/conda/lib/python3.10/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

                             Model  Train Accuracy  Test Accuracy
0               AdaBoostClassifier        1.000000       1.000000
1                BaggingClassifier        1.000000       1.000000
31                   SGDClassifier        1.000000       1.000000
30               RidgeClassifierCV        1.000000       1.000000
29                 RidgeClassifier        1.000000       1.000000
28          RandomForestClassifier        1.000000       1.000000
27       RadiusNeighborsClassifier        1.000000       1.000000
25                      Perceptron        1.000000       1.000000
24     PassiveAggressiveClassifier        1.000000       1.000000
23                           NuSVC        1.000000       1.000000
22                 NearestCentroid        1.000000       1.000000
20                   MLPClassifier        1.000000       1.000000
19            LogisticRegressionCV        1.000000       1.000000
18              LogisticRegression        1.000000       1.000000
17                       LinearSVC        1.000000       1.000000
16      LinearDiscriminantAnalysis        1.000000       1.000000
15                  LabelSpreading        1.000000       1.000000
10       GaussianProcessClassifier        1.000000       1.000000
3           CalibratedClassifierCV        1.000000       1.000000
5           DecisionTreeClassifier        1.000000       1.000000
14                LabelPropagation        1.000000       1.000000
9                       GaussianNB        1.000000       1.000000
8             ExtraTreesClassifier        1.000000       1.000000
11      GradientBoostingClassifier        1.000000       1.000000
12  HistGradientBoostingClassifier        1.000000       1.000000
13            KNeighborsClassifier        1.000000       1.000000
32                             SVC        1.000000       1.000000
2                      BernoulliNB        0.999571       0.999714
7              ExtraTreeClassifier        1.000000       0.987121
26   QuadraticDiscriminantAnalysis        0.971594       0.968804
21                   MultinomialNB        0.889596       0.890956
4                     ComplementNB        0.889596       0.890956
6                  DummyClassifier        0.500000       0.500000

In [14]:
results_df

                             Model  Train Accuracy  Test Accuracy
0               AdaBoostClassifier        1.000000       1.000000
1                BaggingClassifier        1.000000       1.000000
31                   SGDClassifier        1.000000       1.000000
30               RidgeClassifierCV        1.000000       1.000000
29                 RidgeClassifier        1.000000       1.000000
28          RandomForestClassifier        1.000000       1.000000
27       RadiusNeighborsClassifier        1.000000       1.000000
25                      Perceptron        1.000000       1.000000
24     PassiveAggressiveClassifier        1.000000       1.000000
23                           NuSVC        1.000000       1.000000
22                 NearestCentroid        1.000000       1.000000
20                   MLPClassifier        1.000000       1.000000
19            LogisticRegressionCV        1.000000       1.000000
18              LogisticRegression        1.000000       1.000000
17                       LinearSVC        1.000000       1.000000
16      LinearDiscriminantAnalysis        1.000000       1.000000
15                  LabelSpreading        1.000000       1.000000
10       GaussianProcessClassifier        1.000000       1.000000
3           CalibratedClassifierCV        1.000000       1.000000
5           DecisionTreeClassifier        1.000000       1.000000
14                LabelPropagation        1.000000       1.000000
9                       GaussianNB        1.000000       1.000000
8             ExtraTreesClassifier        1.000000       1.000000
11      GradientBoostingClassifier        1.000000       1.000000
12  HistGradientBoostingClassifier        1.000000       1.000000
13            KNeighborsClassifier        1.000000       1.000000
32                             SVC        1.000000       1.000000
2                      BernoulliNB        0.999571       0.999714
7              ExtraTreeClassifier        1.000000       0.987121
26   QuadraticDiscriminantAnalysis        0.971594       0.968804
21                   MultinomialNB        0.889596       0.890956
4                     ComplementNB        0.889596       0.890956
6                  DummyClassifier        0.500000       0.500000